version: '3.8'

services:
  web:
    build: .
    command: python run.py
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes: {}
