"""add_delivery_fields_and_review_tables

Revision ID: 3025ecb0fd22
Revises: c73a4f2c2717
Create Date: 2026-02-27 01:43:39.020416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3025ecb0fd22'
down_revision = 'c73a4f2c2717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_product_review_customer_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_review.review_id'], name=op.f('fk_product_review_parent_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.pro_id'], name=op.f('fk_product_review_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_product_review'))
    )
    op.create_table('vote_tracking',
    sa.Column('vote_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('like', 'dislike', name='vote_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_vote_tracking_customer_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['product_review.review_id'], name=op.f('fk_vote_tracking_review_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id', name=op.f('pk_vote_tracking')),
    sa.UniqueConstraint('review_id', 'customer_id', name='uq_vote_per_user')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_free_delivery', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delivery_charge', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('delivery_charge')
        batch_op.drop_column('is_free_delivery')

    op.drop_table('vote_tracking')
    op.drop_table('product_review')
    # ### end Alembic commands ###
