"""Add product images and bank details

Revision ID: 6ad78af4e10d
Revises: dcd1c74be02e
Create Date: 2026-02-12 18:08:18.408166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad78af4e10d'
down_revision = 'dcd1c74be02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('bank_account_no')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
