"""Add Voucher models

Revision ID: 8e7611d4fe08
Revises: 3025ecb0fd22
Create Date: 2026-03-05 02:04:23.564993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7611d4fe08'
down_revision = '3025ecb0fd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('voucher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('min_cart_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('new_customer_only', sa.Boolean(), nullable=True),
    sa.Column('first_order_only', sa.Boolean(), nullable=True),
    sa.Column('one_time_use', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.cat_id'], name=op.f('fk_voucher_category_id')),
    sa.PrimaryKeyConstraint('voucher_id', name=op.f('pk_voucher'))
    )
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voucher_code'), ['code'], unique=True)

    op.create_table('voucher_usage',
    sa.Column('usage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_voucher_usage_customer_id')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.order_id'], name=op.f('fk_voucher_usage_order_id')),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.voucher_id'], name=op.f('fk_voucher_usage_voucher_id')),
    sa.PrimaryKeyConstraint('usage_id', name=op.f('pk_voucher_usage'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher_usage')
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voucher_code'))

    op.drop_table('voucher')
    # ### end Alembic commands ###
