"""Add account_holder_name to payment

Revision ID: a37e7fb84a12
Revises: 6ad78af4e10d
Create Date: 2026-02-15 23:32:06.225615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37e7fb84a12'
down_revision = '6ad78af4e10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_holder_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('account_holder_name')

    # ### end Alembic commands ###
