"""add brand table and product brand_id

Revision ID: c73a4f2c2717
Revises: a37e7fb84a12
Create Date: 2026-02-20 00:25:09.699919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73a4f2c2717'
down_revision = 'a37e7fb84a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id', name=op.f('pk_brand')),
    sa.UniqueConstraint('brand_name', name=op.f('uq_brand_brand_name'))
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_brand_id'), 'brand', ['brand_id'], ['brand_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_brand_id'), type_='foreignkey')
        batch_op.drop_column('brand_id')

    op.drop_table('brand')
    # ### end Alembic commands ###
